"use client";
import "./globals.css";
import { useEffect } from "react";
import useAuthStore from "./store/useAuthStore";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { setUserToken, setUser, setRestaurantToken, setRestaurant } = useAuthStore();

  useEffect(() => {
    const userToken = localStorage.getItem("userToken");
    const restaurantToken = localStorage.getItem("restaurantToken");

    if (userToken) {
      setUserToken(userToken);
      fetch("/api/user-profile", {
        headers: { Authorization: `Bearer ${userToken}` },
      })
        .then((res) => res.json())
        .then((data) => setUser(data))
        .catch((err) => console.error("Failed to fetch user profile:", err));
    }

    if (restaurantToken) {
      setRestaurantToken(restaurantToken);
      fetch("/api/restaurant-profile", {
        headers: { Authorization: `Bearer ${restaurantToken}` },
      })
        .then((res) => res.json())
        .then((data) => setRestaurant(data))
        .catch((err) => console.error("Failed to fetch restaurant profile:", err));
    }
  }, [setUserToken, setUser, setRestaurantToken, setRestaurant]);
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer
          position="top-center" // 하단 중앙에 위치하도록 설정
          autoClose={5000} // 5초 후 자동 닫힘
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
      </body>
    </html>
  );
}
